heroku config:set GOOGLE_CLIENT_ID=158145275272-lj3m0j741dj9fp50rticq48vtrfu59jj.apps.googleusercontent.com
heroku config:set GOOGLE_CLIENT_SECRET=XvvJaFO2t2lD0mEzNdya6NgT
heroku config:set S3_BUCKET_NAME=your_bucket_name
heroku config:set AWS_ACCESS_KEY_ID=your_access_key_id
heroku config:set AWS_SECRET_ACCESS_KEY=your_secret_access_key
heroku restart